#![warn(clippy::pedantic)]
#![allow(
    clippy::too_many_arguments,
    clippy::similar_names,
    clippy::missing_panics_doc,
    clippy::missing_errors_doc,
    clippy::doc_markdown,
    clippy::default_trait_access,
    //
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_possible_wrap,
    //
    clippy::too_many_lines,
    clippy::type_complexity,
    // generated by cubecl macro
    clippy::format_push_string,
)]
#![recursion_limit = "512"]

pub mod data;
pub mod inference;
pub mod text_generation;
pub mod training;
pub mod ttt;

// Re-export central backend types from ttt module
pub use ttt::{CpuBackend, GpuAutodiffBackend, GpuBackend, TrainingBackend};
