default: build

# Build the project
build:
    mkdir -p build
    cd build && cmake -G Ninja .. && ninja

# Clean build directory
clean:
    rm -rf build

# Run the matrix multiplication program
run: build
    ./build/matmul

# Enter development shell
shell:
    nix develop

# Build using nix
nix-build:
    nix build

# Run using nix build
nix-run: nix-build
    ./result/bin/matmul