default: build

clean:
    rm -rf build/
    rm -f compile_commands.json

configure:
    mkdir -p build
    cd build && cmake .. \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DTTT_PROFILING=ON

build: configure
    cd build && cmake --build . -j$(nproc)
