#![warn(clippy::pedantic)]
#![allow(
    clippy::too_many_arguments,
    clippy::similar_names,
    clippy::missing_panics_doc,
    clippy::missing_errors_doc,
    clippy::doc_markdown,
    clippy::default_trait_access,
    //
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_possible_wrap,
    //
    clippy::too_many_lines,
    clippy::type_complexity,
    // generated by cubecl macro
    clippy::format_push_string,
)]
#![allow(non_camel_case_types, non_snake_case)]

//! TTT Kernel Infrastructure
//!
//! This crate provides the core kernel traits and implementations:
//! - `FusedKernel` - trait for defining fused CubeCL kernels
//! - `FusedKernelBackend` - backend trait for kernel implementations
//! - `TensorBundle` - generic trait for tensor bundles
//! - GELU activation kernels

pub mod bundle;
pub mod gelu;
mod gelu_tanh;
pub mod impls;
pub mod kernel;
pub mod util;

// Re-export commonly used items
pub use bundle::TensorBundle;
pub use gelu::{GeluBwdKernel, GeluInput, GeluOutput, GeluTanhKernel, gelu_bwd, gelu_tanh};
pub use kernel::{FusedKernel, FusedKernelBackend};
